### ISSUE TITLE
create a document-term sparse matrix is not working 

### ISSUE THREAD

**Issue by lokeshpayasi** [dataspelunking/MLwR#1]
create a document-term sparse matrix code is giving error. error is _"Error in simple_triplet_matrix(i, j, v, nrow = length(terms), ncol = length(corpus),  :   'i, j' invalid". how to solve this error.

**Comment by dataspelunking** [comment]
I am very late to responding to this, but I have never been able to reproduce this error. Happy to reopen later if needed.
