### ISSUE TITLE
Unicode / Mojibake errors in CSV

### ISSUE THREAD

**Issue by edent** [dataspelunking/MLwR#2]
For example on https://github.com/dataspelunking/MLwR/blob/master/Machine%20Learning%20with%20R%20(2nd%20Ed.)/Chapter%2004/sms_spam.csv#L79

> Allo! We have braved the buses and taken on the trains and triumphed. I mean we**€˜**re in b**€˜**ham. Have a jolly good rest of week

Should be

> Allo! We have braved the buses and taken on the trains and triumphed. I mean we're in b'ham. Have a jolly good rest of week

There's a few issues like this. Would you accept a PR to fix them?

**Comment by dataspelunking** [comment]
Absolutely! I've tried hunting for all the unicode / ASCII issues but I never seem to catch them all. If you have a fix, I'd happily accept a PR. Thanks!
